### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by hallbi** [blindsidenetworks/wordpress-plugin_bigbluebutton#10]
When activating the plugin downloaded from github yesterday, I got this error msg:
**Fatal error: Arrays are not allowed as constants in /var/www/html/kanalen/wp-content/plugins/wordpress-plugin_bigbluebutton-master/bigbluebutton-plugin.php on line 44**

**Comment by Kalimeiro** [comment]
the code does not seem to have been tested, like a lot of software, does not work for me too, I did differently.

**Comment by WayneBuckhanan** [comment]
That error from November looks like they are using a PHP version earlier than 5.6 (when arrays could first be defined as constants).

**Comment by Kalimeiro** [comment]
(sorry for bad english) sorry to wake you since November Wayne, we do not use PHP 5.6 but more recent, regarding the plugin it just does not work, 1.4.4 works with some problems, but given the responsiveness of the community the patches do not will be shared. **I lost too much time with some developers who think they are gods**.

**Comment by jfederico** [comment]
Sorry pals, the plugin was written in 2010, and not updated for ages :).

Although, I never saw PR from you guys either ;)
